### PR TITLE
Add CV classes to interviewer/interviewee

### PR DESCRIPTION
**Pull request by jechols**

### CODE REVIEW

**Comment by terrellt** [comment]
@kestlund Do you actually want interviewer/interviewee to be controlled, or do you just want URIs to show labels appropriately?

**Comment by kestlund** [comment]
controlled.

**Comment by kestlund** [comment]
@jsimic, please confirm.

**Comment by jsimic** [comment]
Oui!

**Comment by terrellt** [comment]
Okay, then you'll have to add that one namespace that was having a problem to the creator CV.

**Pull request merged**
