### PR TITLE
Don't throw Internal Server Error on access denied

### PR DESCRIPTION
**Pull request by jechols**
Redirects access denied errors using hydra controller behavior code

### CODE REVIEW

**Comment by jechols** [comment]
Probably needs some discussion, as I'm essentially copying code we already have in the hydra controller behavior module.  We could try just pulling that in instead, but I'm guessing we skipped it for a reason.

@terrellt - send me any thoughts you have on this

**Comment by jechols** [comment]
Kicking travis again - all tests passed locally

**Comment by terrellt** [comment]
> We could try just pulling that in instead, but I'm guessing we skipped it for a reason.

I don't think we did. I just didn't know about it for a long time. Do our tests pass if we just include that?

**Comment by jechols** [comment]
After some investigation, it looks like the hydra controller behaviors are pulling into the catalog controller - which is subclass in various places, giving us that rescue_from magic in many places... but not all of them.  Since we don't want all the hydra behaviors in all controllers, but we do want to avoid crashing in all controllers, we decided we'd just leave this rescue_from hack where it is.  More discussions will probably need to happen when we migrate to the newest Hydra stack.

**Pull request merged**
