### PR TITLE
Fix crash on downloading GenericAsset data

### LINKED ISSUE #783: download requiring login instead of IP
Our users can't download the items in our collections that are IP restricted unless they are logged in. We need download regardless of log-in.

Example: http://oregondigital.org/catalog/oregondigital:df661w743

We had a similar problem with the audio download in UOVets, which is totally open (not IP restricted). I do not know why default downloads seem to require log-in. Is this an unintended feature that we got when the restricted for high res downloads was put on some archival photo collections?

### PR DESCRIPTION
**Pull request by jechols**
Closes #783

### CODE REVIEW

**Comment by jechols** [comment]
Ran downloads controller spec locally this time - all seems well there, at least

**Comment by jechols** [comment]
Feature spec failed, looking into it

**Comment by jechols** [comment]
Local specs passed... kicking travis

**Comment by terrellt** [comment]
Does this still restrict full resolution images?

**Comment by jechols** [comment]
Here's the spec that *should* keep full res images protected: https://github.com/OregonDigital/oregondigital/blob/master/spec/controllers/downloads_controller_spec.rb#L6-L24

I think we may still have bugs with full res images if we *want* them to be publicly accessible.  There's no test for those though, and I'm not sure if they even exist.

**Comment by terrellt** [comment]
> I think we may still have bugs with full res images if we want them to be publicly accessible.

I don't think that's a use case yet.

**Pull request merged**
