### PR TITLE
Replace VRA with op_ns

### PR DESCRIPTION
**Pull request by terrellt**

### CODE REVIEW

**Comment by terrellt** [comment]
```
terrellt [3:53 PM] 
So that's because it's mapped right now to VRA.

terrellt [3:53 PM]
@kestlund @jsimic Are we not using VRA at all anymore?

jsimic [3:55 PM] 
VRA isn't officially published, so all the predicates we are using are in op_ns

terrellt [3:55 PM] 
If I switch our mapping in our oregon_rdf file to op_ns for material it'll show all the op_ns materials, but won't show any ingested with vra.

terrellt [3:55 PM]
That okay?

lsato [4:17 PM] 
@terrellt: Julia is standing at my desk and says uo shouldn't have anything with vra predicates.

lsato [4:17 PM]
if we do, it's a mistake
```

That's why I did it. Do we want to add the old VRA predicates in so they show up, until we can clean up those records?

**Comment by jsimic** [comment]
I thought you mean switching from the old (anticipated) VRA predicates in LC (that were not resolving) not removing the /vra/ from the op_ns URIs...

**Comment by terrellt** [comment]
OH

**Comment by terrellt** [comment]
There's a /vra namespace?

**Comment by jsimic** [comment]
http://opaquenamespace.org/ns/vra/blah

**Comment by terrellt** [comment]
=( This means all of AAD is wrong, because it uses http://opaquenamespace.org/ns/measurements.

**Comment by terrellt** [comment]
I'll get this reverted. Thanks @jsimic.

**Comment by terrellt** [comment]
@jsimic That should take care of things.

**Pull request merged**
